application: gitfund
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 6h

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt
  expiration: 6h

- url: /profile.png
  static_files: static/profile.png
  upload: static/profile.png
  expiration: 6h

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 6h

- url: /static
  static_dir: static/assets
  expiration: 6h

- url: /.emoji
  static_dir: static/emoji
  expiration: 6h

- url: .*
  script: gitfund.app
  secure: always
